ros() {
    source /opt/ros/humble/setup.bash
    source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash
    source /usr/share/colcon_cd/function/colcon_cd.sh
    export _colcon_cd_root=/opt/ros/humble/
}

# ros

proxy_on() {
    export http_proxy=http://localhost:7890
    export https_proxy=http://localhost:7890
    export ALL_PROXY=socks5://localhost:7890
}

proxy_off() {
    unset http_proxy
    unset https_proxy
    unset ALL_PROXY
}

proxy_direct() {
    export http_proxy=http://localhost:30001
    export https_proxy=http://localhost:30001
}

proxy_info() {
    echo -e "http_proxy=${http_proxy}"
    echo -e "https_proxy=${https_proxy}"
    echo -e "ALL_PROXY=${ALL_PROXY}"
    curl ipinfo.io
}

export PATH=$HOME/.local/bin:$PATH